//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_FOOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG_HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG_HOADON()
        {
            this.CHITIETDH_HD = new HashSet<CHITIETDH_HD>();
        }
    
        public int MaHD { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayTaoDH { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string SDTGiaoHang { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public System.DateTime NgayGiaoHang { get; set; }
        public string TrangThaiDonHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH_HD> CHITIETDH_HD { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
