//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_FOOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDH_HD
    {
        public int MaHD { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DONHANG_HOADON DONHANG_HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
